//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirkaPrint2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30/19")]
        public string Proisvodstvo_xy {
            get {
                return ((string)(this["Proisvodstvo_xy"]));
            }
            set {
                this["Proisvodstvo_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36/26")]
        public string CodeOborudovoniya_xy {
            get {
                return ((string)(this["CodeOborudovoniya_xy"]));
            }
            set {
                this["CodeOborudovoniya_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30/35")]
        public string SystemUpravleniya_xy {
            get {
                return ((string)(this["SystemUpravleniya_xy"]));
            }
            set {
                this["SystemUpravleniya_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28/42")]
        public string CodeBlocka_xy {
            get {
                return ((string)(this["CodeBlocka_xy"]));
            }
            set {
                this["CodeBlocka_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32/49")]
        public string SerialNumber_xy {
            get {
                return ((string)(this["SerialNumber_xy"]));
            }
            set {
                this["SerialNumber_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32/55")]
        public string Data_xy {
            get {
                return ((string)(this["Data_xy"]));
            }
            set {
                this["Data_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33/64")]
        public string Fio_xy {
            get {
                return ((string)(this["Fio_xy"]));
            }
            set {
                this["Fio_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26/80")]
        public string Neispravnost_xy {
            get {
                return ((string)(this["Neispravnost_xy"]));
            }
            set {
                this["Neispravnost_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20/8")]
        public string Zayavka_xy {
            get {
                return ((string)(this["Zayavka_xy"]));
            }
            set {
                this["Zayavka_xy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StpMode {
            get {
                return ((bool)(this["StpMode"]));
            }
            set {
                this["StpMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32/16")]
        public string STP_P {
            get {
                return ((string)(this["STP_P"]));
            }
            set {
                this["STP_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37/22")]
        public string STP_CO {
            get {
                return ((string)(this["STP_CO"]));
            }
            set {
                this["STP_CO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39/27")]
        public string STP_SU {
            get {
                return ((string)(this["STP_SU"]));
            }
            set {
                this["STP_SU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26/33")]
        public string STP_CB {
            get {
                return ((string)(this["STP_CB"]));
            }
            set {
                this["STP_CB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17/39")]
        public string STP_SN {
            get {
                return ((string)(this["STP_SN"]));
            }
            set {
                this["STP_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40/45")]
        public string STP_D {
            get {
                return ((string)(this["STP_D"]));
            }
            set {
                this["STP_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40/51")]
        public string STP_FIO {
            get {
                return ((string)(this["STP_FIO"]));
            }
            set {
                this["STP_FIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10/71")]
        public string STP_N {
            get {
                return ((string)(this["STP_N"]));
            }
            set {
                this["STP_N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20/7")]
        public string STP_Z {
            get {
                return ((string)(this["STP_Z"]));
            }
            set {
                this["STP_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25/56")]
        public string STP_T {
            get {
                return ((string)(this["STP_T"]));
            }
            set {
                this["STP_T"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Koeff_STP {
            get {
                return ((int)(this["Koeff_STP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Koeff_Normal {
            get {
                return ((int)(this["Koeff_Normal"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Smeshenie {
            get {
                return ((int)(this["Smeshenie"]));
            }
            set {
                this["Smeshenie"] = value;
            }
        }
    }
}
